[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
indicatif = "0.17.8"
rayon = "1.8.1"
itertools = "0.12.1"
